In [ ]:
#for using my video through detect green color
import cv2
import numpy as np
video = cv2.VideoCapture("C:/Users/kiran/Videos/Captures/Learn Colors with Bus Paint _ Finger Family Song for Kids _ Best of Panda Bo - YouTube - Brave 2022-09-12 01-02-00.mp4")

def nothing(x):
    pass
cv2.namedWindow("tra")
cv2.createTrackbar("LH","tra", 0, 255, nothing)
cv2.createTrackbar("LS","tra", 0, 255, nothing)
cv2.createTrackbar("LV","tra", 0, 255, nothing)
cv2.createTrackbar("UH","tra", 0, 255, nothing)
cv2.createTrackbar("US","tra", 0, 255, nothing)
cv2.createTrackbar("UV","tra", 0, 255, nothing)
while True:
    _,cap = video.read()
    
    hsv = cv2.cvtColor(cap, cv2.COLOR_BGR2HSV)
    #L_H =cv2.getTrackbarPos("LH", "tra")
    #L_S =cv2.getTrackbarPos("LS", "tra")
    #L_V =cv2.getTrackbarPos("LV", "tra")
 
    #U_H =cv2.getTrackbarPos("UH", "tra")
    #U_S =cv2.getTrackbarPos("US", "tra")
    #U_V =cv2.getTrackbarPos("UV", "tra")
    
    lower = np.array([36, 25, 25])
    upper = np.array([86, 255,255])
    print(lower, upper)
    mask = cv2.inRange(hsv, (36, 25, 25), (70, 255,255))
    res = cv2.bitwise_and(cap , cap, mask=mask)
    
    cv2.imshow("result",cap)
    cv2.imshow("ok", res )
    #cv2.imshow("mask", mask)
    if cv2.waitKey(1) & 0xFF == ord('p'):
            break
video.release()
# Closes all the frames
cv2.destroyAllWindows()

In [ ]:
video.release()
# Closes all the frames
cv2.destroyAllWindows()

In [1]:
# for image only
import cv2
import numpy as np
def nothing(x):
    pass
cv2.namedWindow("traking")
cv2.createTrackbar("LH","traking", 0, 255, nothing)
cv2.createTrackbar("LS","traking", 0, 255, nothing)
cv2.createTrackbar("LV","traking", 0, 255, nothing)
cv2.createTrackbar("UH","traking", 0, 255, nothing)
cv2.createTrackbar("US","traking", 0, 255, nothing)
cv2.createTrackbar("UV","traking", 0, 255, nothing)
while True:
        
    cap = cv2.imread("C:/Users/kiran/Desktop/Colouring_pencils.jpg")
    hsv = cv2.cvtColor(cap, cv2.COLOR_BGR2HSV)
    L_H =cv2.getTrackbarPos("LH", "traking")
    L_S =cv2.getTrackbarPos("LS", "traking")
    L_V =cv2.getTrackbarPos("LV", "traking")
     
    U_H =cv2.getTrackbarPos("UH", "traking")
    U_S =cv2.getTrackbarPos("US", "traking")
    U_V =cv2.getTrackbarPos("UV", "traking")
    
    lower = np.array([L_H, L_S, L_V])
    upper = np.array([U_H, U_S, U_V])
    print(lower, upper)
    ma = cv2.inRange(hsv, lower, upper)
    res = cv2.bitwise_and(cap , cap, mask = ma)
    
    cv2.imshow("result",cap)
    cv2.imshow("ok", res )
    #cv2.imshow("mask", mask)
    key = cv2.waitKey(1)
    if key == 27:
        break

# Closes all the frames
cv2.destroyAllWindows()


[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] 

[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] 

[0 0 0] [  0 133   0]
[0 0 0] [  0 133   0]
[0 0 0] [  0 133   0]
[0 0 0] [  0 133   0]
[0 0 0] [  0 133   0]
[0 0 0] [  0 133   0]
[0 0 0] [  0 133   0]
[0 0 0] [  0 133   0]
[0 0 0] [  0 133   0]
[0 0 0] [  0 133   0]
[0 0 0] [  0 133   0]
[0 0 0] [  0 133   0]
[0 0 0] [  0 133   0]
[0 0 0] [  0 133   0]
[0 0 0] [  0 141   0]
[0 0 0] [  0 154   0]
[0 0 0] [  0 164   0]
[0 0 0] [  0 176   0]
[0 0 0] [  0 186   0]
[0 0 0] [  0 199   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [  0 201   0]
[0 0 0] [ 

[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [  0 234 255]
[0 0 0] [ 

[ 0  0 51] [204 234 255]
[ 0  0 51] [204 234 255]
[ 0  0 51] [204 234 255]
[ 0  0 51] [204 234 255]
[ 0  0 51] [204 234 255]
[ 0  0 51] [204 234 255]
[ 0  0 51] [204 234 255]
[ 0  0 51] [204 234 255]
[ 0  0 51] [204 234 255]
[ 0  0 51] [204 234 255]
[ 0  0 51] [204 234 255]
[ 0  0 51] [204 234 255]
[ 0  0 51] [204 234 255]
[ 0  0 51] [204 234 255]
[ 0  0 51] [204 234 255]
[ 0  0 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]
[ 0 51 51] [204 234 255]


[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]


[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]


[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]


[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]


[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]


[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]


[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]


[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]


[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]


[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]
[51 51 51] [204 234 255]


In [2]:
#for using my video through detect green color
import cv2
import numpy as np
video = cv2.VideoCapture(0)

def nothing(x):
    pass
cv2.namedWindow("tra")
cv2.createTrackbar("LH","tra", 0, 255, nothing)
cv2.createTrackbar("LS","tra", 0, 255, nothing)
cv2.createTrackbar("LV","tra", 0, 255, nothing)
cv2.createTrackbar("UH","tra", 0, 255, nothing)
cv2.createTrackbar("US","tra", 0, 255, nothing)
cv2.createTrackbar("UV","tra", 0, 255, nothing)
while True:
    _,cap = video.read()
    cap = cv2.resize(cap, (600, 600))
    hsv = cv2.cvtColor(cap, cv2.COLOR_BGR2HSV)
    L_H =cv2.getTrackbarPos("LH","tra")
    L_S =cv2.getTrackbarPos("LS","tra")
    L_V =cv2.getTrackbarPos("LV","tra")
 
    U_H =cv2.getTrackbarPos("UH","tra")
    U_S =cv2.getTrackbarPos("US","tra")
    U_V =cv2.getTrackbarPos("UV","tra")
    
    lower = np.array([L_H,L_S,L_V])
    upper = np.array([U_H,U_S,U_V])
    print(lower, upper)
    ma = cv2.inRange(hsv, lower, upper)
    res = cv2.bitwise_and(cap , cap, mask= ma)
    
    cv2.imshow("result",cap)
    cv2.imshow("ok", res )
    #cv2.imshow("mask", mask)
    if cv2.waitKey(1) & 0xFF == ord('p'):
            break
video.release()
# Closes all the frames
cv2.destroyAllWindows()

[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] [0 0 0]
[0 0 0] 